[package]
name = "lynx-element-bridge-dioxus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
dioxus-core.workspace = true
dioxus-core-macro.workspace = true
dioxus-signals.workspace = true
lynx-element-bridge-core.workspace = true
