[package]
name = "lynx-dioxus-runtime"
description = "Dioxus application runtime for Lynx Element Bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
dioxus-core.workspace = true
lynx-element-bridge-core.workspace = true
lynx-element-bridge-dioxus = { path = "../../adapters/dioxus" }
lynx-element-bridge-wasm-guest.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
lynx-element-bridge-ffi.workspace = true
