[package]
name = "lynx-element-bridge-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
dioxus-core.workspace = true
lynx-element-bridge-core.workspace = true
lynx-element-bridge-dioxus = { path = "../../adapters/dioxus" }
lynx-element-bridge-yew = { path = "../../adapters/yew" }
yew.workspace = true
