[package]
name = "stylist-lynx-cssc"
description = "Experimental Stylist CSS to Lynx ruleList converter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json = "1.0.140"
stylist-core = { version = "=0.15.1", features = ["parser"] }
